export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const GET_JOB_OFFER = 'GET_JOB_OFFER';
export const GET_JOB_OFFERS = 'GET_JOB_OFFERS';
export const GET_COMPANY_JOB_OFFERS = 'GET_COMPANY_JOB_OFFERS';
export const ADD_JOB_OFFER = 'ADD_JOB_OFFER';
export const DELETE_JOB_OFFER = 'DELETE_JOB_OFFER';
export const JOB_OFFERS_ERROR = 'JOB_OFFERS_ERROR';
export const CLEAR_JOBS_ERRORS = 'CLEAR_JOBS_ERRORS';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANIES = 'GET_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const CLEAR_CURRENT_COMPANY = 'CLEAR_CURRENT_COMPANY';
export const COMPANY_ERROR = 'COMPANY_ERROR';
export const CLEAR_COMPANIES_ERRORS = 'CLEAR_COMPANIES_ERRORS';

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
export const ADD_TO_RECENTLY_VISITED = 'ADD_TO_RECENTLY_VISITED';
export const REMOVE_FROM_RECENTLY_VISITED = 'REMOVE_FROM_RECENTLY_VISITED';
