export const companies = [
  {
    companyId: 0,
    companyName: 'UI CENTER SGS',
    country: 'Poland',
    province: 'Śląskie',
    postalCode: '40-001',
    city: 'Katowice',
    address: 'Mickiewicza 29b',
    companySize: 30,
    logo: './assets/company-logo.png',
    //album zdjęć, url do profilu
  },
  {
    id: 1,
    companyName: 'CodeOne',
    country: 'Poland',
    province: 'Mazowieckie',
    postalCode: '41-213',
    city: 'Warszawa',
    address: 'Piłsudskiego 12',
    companySize: 60,
    logo: './assets/company-logo.png',
    //album zdjęć, url do profilu
  },
  {
    id: 2,
    companyName: 'Frontify',
    country: 'Poland',
    province: 'Śląskie',
    postalCode: '40-021',
    city: 'Gliwice',
    address: 'Hutnicza 34',
    companySize: 10,
    logo: './assets/company-logo.png',
    //album zdjęć, url do profilu
  },
];

export const jobAdvertisements = [
  {
    jobAdvertisementId: 0,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'UI/UX designer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: null,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 1,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 2,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 3,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 4,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
];

export const categories = [
  { categoryId: 0, categoryName: 'Frontend developer' },
  { categoryId: 1, categoryName: 'Backend developer' },
  { categoryId: 2, categoryName: 'Fullstack developer' },
  { categoryId: 3, categoryName: 'DevOps engineer' },
  { categoryId: 4, categoryName: 'UX designer' },
];
