export const companies = [
  {
    companyId: 0,
    companyName: 'UI CENTER SGS',
    country: 'Poland',
    province: 'Śląskie',
    postalCode: '40-001',
    city: 'Katowice',
    address: 'Mickiewicza 29b',
    companySize: 30,
    logo: './assets/company-logo.png',
    //album zdjęć, url do profilu
  },
  {
    id: 1,
    companyName: 'CodeOne',
    country: 'Poland',
    province: 'Mazowieckie',
    postalCode: '41-213',
    city: 'Warszawa',
    address: 'Piłsudskiego 12',
    companySize: 60,
    logo: './assets/company-logo.png',
    //album zdjęć, url do profilu
  },
  {
    id: 2,
    companyName: 'Frontify',
    country: 'Poland',
    province: 'Śląskie',
    postalCode: '40-021',
    city: 'Gliwice',
    address: 'Hutnicza 34',
    companySize: 10,
    logo: './assets/company-logo.png',
    //album zdjęć, url do profilu
  },
];

export const jobAdvertisements = [
  {
    jobAdvertisementId: 0,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'Hitachi Energy',
    province: 'Małopolskie',
    city: 'Kraków',
    jobTitle: 'C# Developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 9000,
    salaryTo: 16000,
    duties: [
      'Achieving business goals through designing and developing code in the .NET technologies',
      'Assuring high code quality through unit tests and adherence to software development best practices like Clean Code, SOLID and code reviews ',
      `Improving technical skills and knowledge of the project's business domain `,
      'Being a member of a cross-disciplinary team (active participation in team activities that focus on a common goal).',
    ],
    requirements: [
      'More than 3 years of professional experience in software development ',
      'Experience in the .NET technology stack: C#, REST Web Services, .Net Core ',
      'Good knowledge of the Unit and Integration testing technics and frameworks ',
      'Good understanding of the microservices architecture and related topics (for example, message queues) ',
      'Knowledge of DDD, Event Sourcing, CQRS, gRPC, Kubernetes or Helm Charts is a plus ',
      'Effective team player with excellent communication skills who is eager to learn new things ',
      'Good spoken and written English.',
    ],
    benefits: [
      'Healthcare package',
      'Healthcare package for families',
      'Leisure package',
      'Conferences',
      'Trainings',
      'Books',
      'Language courses',
      'Relocation package',
      'Teams integration and company events',
      'MS Office license',
      'Multicafeteria',
      'Life insurance',
    ],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 1,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: null,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 2,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'ONWELO SA',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Front-end Developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 9000,
    salaryTo: 18900,
    duties: [
      'Projektować nowoczesne rozwiązania dla klientów Onwelo ',
      'Tworzyć oprogramowanie, współpracując z doświadczonymi programistami ',
      'Współpracować z kierownikami projektów, analitykami, testerami, klientami i innymi specjalistami, aby upewnić się, że potrzeby biznesowe są spełniane ',
      'Omawiać sposoby rozwiązań problemów programistycznych i architektonicznych ',
      'Testować i opiniować nowe technologie i nowe rozwiązania dla klientów ',
      'Realizować testy jednostkowe i integracyjne ',
      'Rozwijać proces dostarczania oprogramowania w metodyce DevOps ',
      'Poznawać nowe koncepcje programowania i nowości architektoniczne ',
      'Obserwować w działaniu swoje oprogramowanie w środowisku produkcyjnym',
    ],
    requirements: [
      'Posiadasz min. 2 lata doświadczenia komercyjnego w technologiach front-endowych ',
      'Znasz technologie: JavaScript, TypeScript, HTML, CSS (SASS, LESS)',
      'Bardzo dobrze czujesz się w pracy z wykorzystaniem frameworka Angular lub/oraz React',
      'Pracowałeś z wykorzystaniem bibliotek RxJS lub/oraz Redux ',
      'Wiesz, jak tworzyć czysty i przejrzysty kod ',
      'Potrafisz pisać testy z wykorzystaniem narzędzi do testowania ',
      'Znasz standardy nazewnictwa i wzorce projektowe ',
      'Znasz język angielski na poziomie pozwalającym na swobodną komunikację i uczestniczenie w międzynarodowym projekcie ',
      'Potrafisz tworzyć dokumentację projektową',
    ],
    benefits: [
      'Pakiet medyczny',
      'Pakiet medyczny dla rodziny',
      'Pakiet sportowy',
      'Pakiet sportowy dla rodziny',
      'Szkolenia',
      'Konferencje',
      'Premia za polecenie Pracownika',
    ],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 3,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 4,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 5,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 6,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 7,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 8,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 9,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
  {
    jobAdvertisementId: 10,
    background: './assets/company-background.png',
    logo: './assets/company-logo.png',
    company: 'UI CENTER SGS',
    province: 'Śląskie',
    city: 'Katowice',
    jobTitle: 'Backend developer',
    employmentType: ['B2B', 'UoP'],
    seniorityLevel: 'Mid',
    remoteRecruitment: true,
    remoteJob: true,
    workingHours: ['full time'],
    salaryFrom: 8000,
    salaryTo: 12000,
    duties: [
      'Rozwój i utrzymanie wydajnego i skalowalnego kodu opartego o odpowiednie wzorce projektowe',
      'Analiza wymagań biznesowych i udział w definiowaniu zadań',
      'Implementacja kluczowych funkcjonalności w systemie',
      'Przeprowadzanie code review dla innych członków zespołu',
      'Podejmowanie decyzji technologicznych i architektonicznych',
      'Optymalizacja i refaktoryzacja kodu w razie potrzeby, redukowanie długu technologicznego',
    ],
    requirements: [
      '3 lat doświadczenia w tworzeniu w Python',
      'bardzo dobra znajomość języka Python oraz umiejętność programowania zorientowanego obiektowo,',
      'dobra znajomość języka SQL oraz baz relacyjnych danych (PostgreSQL),',
      'umiejętność posługiwania się systemem kontroli wersji GIT',
      'doświadczenie w tworzeniu komercyjnych projektów',
      'znajomość języka angielskiego w stopniu komunikatywnym',
    ],
    benefits: ['Pakiet Medicover', 'Darmowy parking', 'Rest room'],
    remainingAnnocementTime: 11,
  },
];

export const categories = [
  { categoryId: 0, categoryName: 'Frontend developer' },
  { categoryId: 1, categoryName: 'Backend developer' },
  { categoryId: 2, categoryName: 'Fullstack developer' },
  { categoryId: 3, categoryName: 'DevOps engineer' },
];
